### ISSUE TITLE
Error translation with Chinese

### ISSUE THREAD

**Issue by KongCon** [aspnet/Docs.zh-cn#101]
Call the UseAuthentication method before calling UseMvcWithDefaultRoute or UseMvc:
"调用UseAuthentication方法之前调用UseMvcWithDefaultRoute或UseMvc:"

Shoule be translated as 
"在调用UseMvcWithDefaultRoute或UseMvc方法之前调用UseAuthentication:"

**Comment by CeciAc** [comment]
Hello, @KongCon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
@CeciAc He himself have fixed this in #102

**Comment by CeciAc** [comment]
Thanks for the clarification, @imba-tjd 
I'm closing this issue now
