### ISSUE TITLE
key content missing in the  tutorial  

### ISSUE THREAD

**Issue by lawushanshan** [aspnet/Docs.zh-cn#109]
Hi,its a good time when learning this tutorial,but i have some trouble at the end of the tutoral  &lt;Razor page with Ef core in aspnetcore - Datamodel-5 of 8&gt;,The Title " Fix the ForeignKey constrants" lose key codes when add  ForeignKey without drop database,hope to fixing it ,Thanks

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [ASP.NET Core 中的 Razor 页面和 EF Core - 数据模型 - 第 5 个教程（共 8 个）](https://docs.microsoft.com/zh-cn/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=netcore-cli#applyexisting)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/docs.zh-cn/blob/live/aspnetcore/data/ef-rp/complex-data-model.md)
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://github.com/aspnet/Docs/issues/10638

**Comment by LisandroSu** [comment]
Hi @lawushanshan thanks for your feedback!

@Rick-Anderson Can we close this Docs.zh-cn issue? Thanks!

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Can we close this Docs.zh-cn issue?

Yes.

**Comment by Rick-Anderson** [comment]
Closing as These steps work only if you skipped the preceding Drop and re-create the database section.

**Comment by LisandroSu** [comment]
Closing the Issue. Thanks!
