### ISSUE TITLE
[Web Api]Bind 特性不起作用

### ISSUE THREAD

**Issue by zhangxuanbin2049** [aspnet/Docs.zh-cn#129]
文档：[Web API应用—教程—使用MongoDB的Web API](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-2.2&tabs=visual-studio)
` namespace Books.Api.Controllers`
` [HttpPost]`
` public ActionResult<Book> Create([Bind("BookName, Price, Category, Author")] Book book)`
描述：当我使用postman测试post方法时，包含id仍可成功录入，bind特性不起作用。
<img width="769" alt="批注 2019-04-20 133741" src="https://user-images.githubusercontent.com/38483786/56453219-bf183600-6371-11e9-93cb-125ee3be7d96.png">

**Comment by zhangxuanbin2049** [comment]
> 描述：当我使用postman测试post方法时，包含id仍可成功录入，bind特性不起作用。

**Comment by CeciAc** [comment]
你好，@zhangxuanbin2049
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
