### ISSUE TITLE
ASP.NET Core MVC和EF Core入门文档中文翻译

### ISSUE THREAD

**Issue by FOWind** [aspnet/Docs.zh-cn#18]
# ASP.NET Core MVC和EF Core入门文档中文翻译
[APS.NET Core MVC 和 EF Core中文文档](https://docs.microsoft.com/zh-cn/aspnet/core/data/ef-mvc/)下面的文档都是使用机器翻译的，希望能够有手工翻译的文档。

**Comment by SunnyDeng** [comment]
Transform to en-us for further action item: 

APS.NET Core MVC and EF Core Chinese Document are all machine Translated, hope to see Manuel Translated document.

**Comment by CeciAc** [comment]
Issue reffers to a previous version. Actual page is HT.
