### ISSUE TITLE
关于社区协作规范

### ISSUE THREAD

**Issue by chsword** [aspnet/Docs.zh-cn#23]
首先，如果想要有高质量的文档，肯定是不能只依靠机器翻译，机器翻译也不是那么靠谱。

我建议由管理人员编写一个社区规范，这样也方便关注此项目的开发者可以方便地参加进来。

当前 repository 既然是中文文档，社区规范是可以由中文编写的，可以在 Wiki 中，或者直接使用一个 MD。

其中我觉得可以包括：
1. 分支与 PR 的规范
1. 文档书写规范

等等吧

@olprod 看看是否有这样的计划

**Comment by FOWind** [comment]
我翻译了ef-mvc的前三篇文章，发了pull-request，能不能帮忙看一下。说实话我也是初学者，看到那一塌糊涂的机器翻译，就忍不住动手翻译了一波，至少比机器翻译的容易看懂。有易懂的中文文档才能帮助中文开发者更好的入门啊！

**Comment by terrysheng** [comment]
@chsword @FOWind 
感谢您们的反馈, 关于规范, 可以参考
https://www.microsoft.com/en-us/language/StyleGuides
希望会有些帮助:)
