### ISSUE TITLE
人工翻译被覆盖的问题

### ISSUE THREAD

**Issue by chsword** [aspnet/Docs.zh-cn#26]
您好，我的这次提交是人工翻译，但是被机器翻译覆盖的，请问如何处理
https://github.com/aspnet/Docs.zh-cn/commit/62f82277bc388acaf27b0da79cd565cd22ba6111#diff-0ab874d3c46dbab0a8bbc01210869cea

**Comment by imba-tjd** [comment]
> Thank you for your feedback and suggestion!
>
> The suggestion will be merged to the production, we will re-release this articles in the next loc release round.
>
> Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hello, @chsword ,  
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/error-handling.  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
