### ISSUE TITLE
官方文档Dependency injection页面显示的是英文原版

### ISSUE THREAD

**Issue by HeMinzhang** [aspnet/Docs.zh-cn#47]
官方文档Dependency injection in ASP.NET Core链接：
https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1
指向的是原版链接
https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md
但是中文版的链接
https://github.com/aspnet/Docs.zh-cn/blob/live/aspnetcore/fundamentals/dependency-injection.md
2个月前已经汉化了

**Comment by CeciAc** [comment]
你好，@HeMinzhang

感谢你的反馈。 

我们正在积极查看你的评论，并会很快地再次和你取得联系。 

深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@HeMinzhang
感谢你的反馈。

该链接现在正常工作。

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。

深深的祝福，
