### ISSUE TITLE
文档中多处出现[!code-csharp]

### ISSUE THREAD

**Issue by nbyh** [aspnet/Docs.zh-cn#50]
文档中多处出现[!code-csharp]，没有具体代码示例。

**Comment by CeciAc** [comment]
你好，@nbyh 

感谢你的反馈。 

我们正在积极查看你的评论，并会很快地再次和你取得联系。 

深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@nbyh

感谢你的反馈。

我们正在积极查看你的评论，并会很快地再次和你取得联系。

深深的祝福，
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@nbyh
没有足够的信息来处理此请求。

欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team

**Comment by nbyh** [comment]
“没有足够的信息来处理此请求。”是什么情况？为什么呢？文档中很多[!code-csharp]，比如“使用 ASP.NET Core 构建 Web API”章节里的内容。
![20180606155618](https://user-images.githubusercontent.com/7239908/41024606-4b99ee72-69a2-11e8-873d-92c421b8c244.png)

**Comment by yichaoo** [comment]
是的，我也是这种情况，之前还可以看到示例代码，现在大部份显示的[!code-csharp]
