### ISSUE TITLE
为什么大部份代码无法显示，而只是显示[!code-xml]或[!code-csharp]

### ISSUE THREAD

**Issue by yichaoo** [aspnet/Docs.zh-cn#52]
为什么大部份代码无法显示，而只是显示[!code-xml]或[!code-csharp]
例如：
https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1
![pic](https://user-images.githubusercontent.com/20152597/41334462-48259c02-6f18-11e8-8f44-0f15334f1148.png)

**Comment by yichaoo** [comment]
其它错误如下，没有代码示例，很难参考学习
![323](https://user-images.githubusercontent.com/20152597/41334548-97404422-6f18-11e8-9ac0-7be193c011bd.png)

**Comment by CeciAc** [comment]
你好，@yichaoo
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team
