### ISSUE TITLE
The link is 404.

### ISSUE THREAD

**Issue by HeMinzhang** [aspnet/Docs.zh-cn#56]
this page:
https://docs.microsoft.com/zh-cn/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.1
 link to github is 404:
https://github.com/aspnet/docs.zh-cn/blob/live/aspnetcore/signalr/dotnet-client.md

**Comment by v-maudel** [comment]
你好，@HeMinzhang , 

感谢你的反馈。 

我们正在积极查看你的评论，并会很快地再次和你取得联系。 

深深的祝福， 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
你好，@HeMinzhang

感谢你的反馈。 

我们的工程团队已评审并接受你的建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.1。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
