### ISSUE TITLE
Shouldn't we add a blankspace after an English word followed with Chinese character?

### ISSUE THREAD

**Issue by imba-tjd** [aspnet/Docs.zh-cn#58]
Hi, I don't understand the following commits mean what:
https://github.com/aspnet/Docs.zh-cn/commit/cb2cd874012590f0d99637d239682ae1a3bc300c
https://github.com/aspnet/Docs.zh-tw/commit/4ecf0266b62ab11fb7ebec46be90e3b8a8efc3a6
https://github.com/aspnet/EntityFramework.Docs.zh-cn/commit/15a20a37ebfdf3ba6e48e4e4421fb29aebaeb0c9
https://github.com/aspnet/EntityFramework.Docs.zh-tw/commit/3cc8eef708af7fcbb28937265d1a16714423e83a

According to existing documentation, we **should** add a blankspace after an English word followed with Chinese character.
If so, these commits needs to be reverted. Except that the first two commits have extra modification to `aspnetcore/web-api/index.md` which shouldn't be reverted.

**Comment by gosali** [comment]
Hello, @imba-tjd ,  

Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the affected pages.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
Hi, @gosali

> Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the affected pages.

If `linguist suggestions` means this issue itself, then fine. Close this when fixed (I hasn't seen it's fixed yet).

But if you mean those PRs I created before, your localization team did accepted them. However they made a wrong change as I mentioned above:joy:.

**Comment by imba-tjd** [comment]
OK. Issue has been fixed now.:ghost:

**Comment by imba-tjd** [comment]
Things are always different from what I think...
Anyway, your team still needs to revert:
https://github.com/aspnet/Docs.zh-tw/commit/4ecf0266b62ab11fb7ebec46be90e3b8a8efc3a6#diff-dd27d54360d767c4034670b8601ccaac
https://github.com/aspnet/EntityFramework.Docs.zh-cn/commit/15a20a37ebfdf3ba6e48e4e4421fb29aebaeb0c9#diff-e4619d29eb84f51b85b5596bc6f65de6

**Comment by imba-tjd** [comment]
Oops... I'm sorry. Your team really fixed this issue...
The reason why I did't see is because I only checked the first files of these two commits and they are still unfixed. But it seems that your team fixed others.
