### ISSUE TITLE
filesize

### ISSUE THREAD

**Issue by ClementeGao** [aspnet/Docs.zh-cn#65]
What is the maximum number of files uploaded at one time?for IFormFile

**Comment by LisandroSu** [comment]
Hello, @ClementeGao , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
