### ISSUE TITLE
How to deploy an unpublished dotnet-core project on iis like a dotnet project

### ISSUE THREAD

**Issue by pikadun** [aspnet/Docs.zh-cn#70]
我可以直接在iis上部署一个未发布的.net web项目，只要将项目目录指向工程目录就可以了；
但是我用同样的方法无法正确部署.net core项目，当我访问某个URL时，会得到404的页面。

![tim 20180813092603](https://user-images.githubusercontent.com/32519715/44009019-5957bdc8-9edb-11e8-861a-28b6247e53d9.png)
![tim 20180813092629](https://user-images.githubusercontent.com/32519715/44009022-59ab146e-9edb-11e8-92bb-2d328e1a21f0.png)
![tim 20180813093238](https://user-images.githubusercontent.com/32519715/44009111-dcb19ab8-9edb-11e8-9e06-b3e9272a78dd.png)

**Comment by LisandroSu** [comment]
你好，@pikadun

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
