### ISSUE TITLE
No code is displayed on the page

### ISSUE THREAD

**Issue by hjkl950217** [aspnet/Docs.zh-cn#72]
Error URL:https://docs.microsoft.com/zh-cn/aspnet/core/performance/caching/memory?view=aspnetcore-2.0

have code show in the page.
search '可以通过设置缓存项的大小大小或SetSize扩展方法' show the error words.Use ctrl+f

**Comment by LisandroSu** [comment]
Hello, @hjkl950217, 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @hjkl950217,

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/aspnet/core/performance/caching/memory?view=aspnetcore-2.0. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
