### ISSUE TITLE
页面模型还是页模型？

### ISSUE THREAD

**Issue by gqqnbig** [aspnet/Docs.zh-cn#73]
[aspnetcore/fundamentals/configuration/options.md](aspnetcore/fundamentals/configuration/options.md)

**页面模型**出现1次，**页模型**出现2次。

还有一个翻译是页上的模型，这肯定不对。

请问到底要用页面模型还是页模型？

**Comment by LisandroSu** [comment]
你好，@gqqnbig
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
你好，@gqqnbig

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：aspnetcore/fundamentals/configuration/options.md。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team

**Comment by gqqnbig** [comment]
深深的感谢
