### ISSUE TITLE
The commands in the docs does not work

### ISSUE THREAD

**Issue by JinGangRed** [aspnet/Docs.zh-cn#78]
When I use the command

>  dotnet new webapp -o aspcoreapp

I get the error: `There is no template matching input template name: webapp`.

I changed the command following the suggest template like this:

>  dotnet new web -o aspcore app

It works.

And the other command:

> dotnet dev-certs https --trust

I get the error:` No executable file matching the command "dotnet-dev-certs" was found`.

And the version of the dotnet like this:
![image](https://user-images.githubusercontent.com/26211024/47073714-78634b00-d22b-11e8-92b3-4e7c8019ce6d.png)

**Comment by imba-tjd** [comment]
给个链接啊，你这要别人怎么找

**Comment by LisandroSu** [comment]
Hello, @JinGangRed 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @JinGangRed,
 
We are following up on our previous comment. We need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by JinGangRed** [comment]
The link is: https://docs.microsoft.com/zh-cn/aspnet/core/getting-started/?view=aspnetcore-2.1&tabs=windows

**Comment by CeciAc** [comment]
Issue moved to [aspnet/Docs #9251](https://github.com/aspnet/Docs/issues/9251) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @JinGangRed,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/Docs/issues/9251.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
